### PR TITLE
ensure all span closed before sending span

### LINKED ISSUE #37: sending report after skywalking server restart causes SIGABRT with pure virtual method called
steps to reproduce:

1. start client
2. restart skywalking server
3. send report to skywalking server

same issue:
https://www.mail-archive.com/grpc-io@googlegroups.com/msg00942.html

```
doing two async operations together in your server... Instead try one operation at a time...
```

traced to this line:
https://github.com/SkyAPM/cpp2sky/blob/4d435c9d45aebfbeda6250f82075f35e711b995e/source/grpc_async_client_impl.cc#L154

after quoting  `request_writer_->Finish(&status_, toTag(&finish_));`  the problem went away.

BTW: calling `request_writer_->Finish(&status_, toTag(&finish_));` in destructor is an obvious mistake, because it passes fields like status_/finish_ to an async call,  these fields will be accessed later, but by then the stream object has been desctructed.

### PR DESCRIPTION
**Pull request by Shikugawa**
It also closes #37

### CODE REVIEW

File: source/segment_context_impl.cc [hunk 1]
```diff
@@ -251,6 +252,15 @@ SegmentObject SegmentContextImpl::createSegmentObject() {
   return obj;
 }
 
+bool SegmentContextImpl::readyToSend() {
```
Comment (wu-sheng) [inline source/segment_context_impl.cc:255]: I want to confirm about the purpose of this method. In the previous(other languages) implementations, the condition to determine sending segment is
**All spans created in this context(linked to this segment) have stopped**

What is the special case of async for cpp? In Java, we take care of this by using a set of separated APIs, because it used ThreadLocal(binding context with thread), but I believe cpp is not that thing.
Java APIs, https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#async-span-apis

Comment (Shikugawa) [reply source/segment_context_impl.cc:255]: This had introduced not for async context. Only to achieve the requirement that all spans belong to this segment must be stopped.

Comment (Shikugawa) [reply source/segment_context_impl.cc:255]: And, current envoy's implementation has guarantee not to be sent if current segment doesn't have unfinished span. So It was introduced for backward compatibility.

Comment (wu-sheng) [reply source/segment_context_impl.cc:255]: Then, what is the real case the span doesn't stop? Is that caused by user's codes?

Comment (Shikugawa) [reply source/segment_context_impl.cc:255]: Yes. the problem can be caused from user's codes in the current implementation. (User may forget to stop them) I'd like to introduce RAII (start span and automatically end span when current scope finished) based approach to protect this but not now.

**Review by wu-sheng — APPROVED** [review]
